import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

const syncCols = {
  serverId: text('server_id'),
  syncStatus: text('sync_status').notNull().default('local'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  deletedAt: timestamp('deleted_at'),
};

export const eaUsers = pgTable('ea_users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  fullName: text('full_name'),
  role: text('role').notNull().default('inspector'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const eaAudits = pgTable('ea_audits', {
  id: text('id').primaryKey(),
  ...syncCols,
  siteName: text('site_name').notNull(),
  siteAddress: text('site_address').notNull(),
  inspectorName: text('inspector_name').notNull(),
  auditDate: text('audit_date'),
  status: text('status').notNull().default('Draft'),
  reportPdfLocalPath: text('report_pdf_local_path'),
  reportPdfRemoteUrl: text('report_pdf_remote_url'),
  createdByUserId: text('created_by_user_id'),
  assignedInspectorUserId: text('assigned_inspector_user_id'),
  startedAt: timestamp('started_at'),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaAuditWorkSessions = pgTable('ea_audit_work_sessions', {
  id: text('id').notNull(),
  auditId: text('audit_id')
    .notNull()
    .references(() => eaAudits.id, { onDelete: 'cascade' }),
  actorUserId: text('actor_user_id').notNull(),
  startedAt: timestamp('started_at').notNull(),
  lastActiveAt: timestamp('last_active_at').notNull(),
  endedAt: timestamp('ended_at'),
  activeMilliseconds: bigint('active_milliseconds', { mode: 'number' }).notNull(),
  revision: integer('revision').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
}, (table) => [
  primaryKey({
    columns: [table.auditId, table.id],
    name: 'ea_audit_work_sessions_pk',
  }),
  index('ea_audit_work_sessions_audit_actor_idx').on(
    table.auditId,
    table.actorUserId,
    table.updatedAt,
  ),
  check(
    'ea_audit_work_sessions_active_milliseconds_check',
    sql`${table.activeMilliseconds} >= 0`,
  ),
  check('ea_audit_work_sessions_revision_check', sql`${table.revision} >= 0`),
  check(
    'ea_audit_work_sessions_time_order_check',
    sql`${table.startedAt} <= ${table.lastActiveAt}
      AND (${table.endedAt} IS NULL OR ${table.lastActiveAt} <= ${table.endedAt})`,
  ),
]);

export const eaZones = pgTable('ea_zones', {
  id: text('id').primaryKey(),
  ...syncCols,
  auditId: text('audit_id').notNull(),
  zoneName: text('zone_name').notNull(),
  zoneDescription: text('zone_description'),
  photos: text('photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaMainSwitchboards = pgTable('ea_main_switchboards', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  name: text('name').notNull(),
  location: text('location'),
  mapLocator: text('map_locator'),
  siteNmi: text('site_nmi'),
  photo: text('photo'),
  subCircuitsDescription: text('sub_circuits_description'),
  comments: text('comments'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaAdditionalSwitchboards = pgTable('ea_additional_switchboards', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  name: text('name').notNull(),
  location: text('location'),
  mapLocator: text('map_locator'),
  type: text('type'),
  photo: text('photo'),
  subCircuitsDescription: text('sub_circuits_description'),
  comments: text('comments'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaHvacUnits = pgTable('ea_hvac_units', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  unitName: text('unit_name').notNull(),
  make: text('make'),
  photo: text('photo'),
  location: text('location'),
  type: text('type'),
  model: text('model'),
  serialNumber: text('serial_number'),
  heatingCapacityKw: real('heating_capacity_kw'),
  coolingCapacityKw: real('cooling_capacity_kw'),
  powerSupplyPhase: text('power_supply_phase'),
  nameplatePhotos: text('nameplate_photos'),
  indoorUnitModel: text('indoor_unit_model'),
  indoorUnitSerial: text('indoor_unit_serial'),
  indoorUnitNameplatePhoto: text('indoor_unit_nameplate_photo'),
  controllerType: text('controller_type'),
  controllerModel: text('controller_model'),
  controllerPhoto: text('controller_photo'),
  temperatureSensorType: text('temperature_sensor_type'),
  systemCoverage: text('system_coverage'),
  energyImprovementObservations: text('energy_improvement_observations'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaLightingSystems = pgTable('ea_lighting_systems', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  lightType: text('light_type').notNull(),
  brandModel: text('brand_model'),
  photo: text('photo'),
  ratedWattage: real('rated_wattage'),
  quantity: integer('quantity'),
  fixturesInstalled: text('fixtures_installed'),
  fixturesPhoto: text('fixtures_photo'),
  areaLocation: text('area_location'),
  controlsType: text('controls_type'),
  operatingHours: text('operating_hours'),
  mountingHeight: text('mounting_height'),
  mountingConstraintsPhoto: text('mounting_constraints_photo'),
  circuitGrouping: text('circuit_grouping'),
  sensorsPhoto: text('sensors_photo'),
  accessLimitations: text('access_limitations'),
  // Keep the legacy physical column for compatibility with existing data, but
  // expose the same field name used by the mobile domain model and PDF metadata.
  switchboardControlsPhoto: text('switchboard_photo_notes'),
  energyImprovementObservations: text('energy_improvement_observations'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaSolarPv = pgTable('ea_solar_pv', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  systemSizeKw: real('system_size_kw'),
  roofPhoto: text('roof_photo'),
  inverterBrandModel: text('inverter_brand_model'),
  inverterLocation: text('inverter_location'),
  inverterLabelPhoto: text('inverter_label_photo'),
  powerSupplyToPv: text('power_supply_to_pv'),
  electricityMeterPhoto: text('electricity_meter_photo'),
  availableRoofSpace: text('available_roof_space'),
  roofSpaceAmount: text('roof_space_amount'),
  additionalSolarSpacePhoto: text('additional_solar_space_photo'),
  suitableSwitchboard: text('suitable_switchboard'),
  switchboardPhoto: text('switchboard_photo'),
  switchboardLocation: text('switchboard_location'),
  cableDistance: text('cable_distance'),
  cableRouteDescription: text('cable_route_description'),
  energyImprovementObservations: text('energy_improvement_observations'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaForkliftChargers = pgTable('ea_forklift_chargers', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  chargerType: text('charger_type').notNull(),
  chargerPhoto: text('charger_photo'),
  brandModel: text('brand_model'),
  rating: text('rating'),
  chargerLabelPhoto: text('charger_label_photo'),
  powerSupply: text('power_supply'),
  electricConnectionPhoto: text('electric_connection_photo'),
  location: text('location'),
  quantity: integer('quantity'),
  chargerSpacePhoto: text('charger_space_photo'),
  connectionDescription: text('connection_description'),
  socketConnectionPhoto: text('socket_connection_photo'),
  localIsolator: text('local_isolator'),
  circuitIdentifiable: text('circuit_identifiable'),
  distanceToSwitchboard: text('distance_to_switchboard'),
  spaceForAdditional: text('space_for_additional'),
  hardwiredSocket: text('hardwired_socket'),
  schedulingOpportunity: text('scheduling_opportunity'),
  energyImprovementObservations: text('energy_improvement_observations'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaHotWaterSystems = pgTable('ea_hot_water_systems', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  dhwDetailsType: text('dhw_details_type').notNull(),
  photo: text('photo'),
  serialNumber: text('serial_number'),
  sizeLiters: real('size_liters'),
  fuelType: text('fuel_type'),
  location: text('location'),
  pipeInsulation: text('pipe_insulation'),
  pipeInsulationThickness: text('pipe_insulation_thickness'),
  temperingValve: text('tempering_valve'),
  additionalPhoto: text('additional_photo'),
  moreDhwSystems: text('more_dhw_systems'),
  additionalComments: text('additional_comments'),
  energyImprovementObservations: text('energy_improvement_observations'),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaGeneralWater = pgTable('ea_general_water', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  question: text('question'),
  answer: text('answer'),
  photos: text('photos').array().notNull().default([]),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const eaGeneralElectricity = pgTable('ea_general_electricity', {
  id: text('id').primaryKey(),
  ...syncCols,
  zoneId: text('zone_id').notNull(),
  auditId: text('audit_id').notNull(),
  question: text('question'),
  answer: text('answer'),
  photos: text('photos').array().notNull().default([]),
  extraNotes: text('extra_notes'),
  extraPhotos: text('extra_photos').array().notNull().default([]),
  photoDescs: jsonb('photo_descs').notNull().default({}),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});
