import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

const syncCols = {
  serverId: text('server_id'),
  syncStatus: text('sync_status').notNull().default('local'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  deletedAt: timestamp('deleted_at'),
};

export const ssUsers = pgTable('ss_users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  fullName: text('full_name'),
  role: text('role').notNull().default('inspector'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const ssSites = pgTable('ss_sites', {
  id: text('id').primaryKey(),
  ...syncCols,
  siteName: text('site_name').notNull(),
  location: text('location'),
  dateOfAssessment: text('date_of_assessment'),
  documentClassification: text('document_classification'),
  electricalInfrastructureSummary: text('electrical_infrastructure_summary'),
  knownConstraints: text('known_constraints'),
  loadProfileMeteringSummary: text('load_profile_metering_summary'),
  ppaAssetDemarcation: text('ppa_asset_demarcation'),
  appendixNotes: text('appendix_notes'),
  appendixItems: jsonb('appendix_items').notNull().default([]),
  reportPdfLocalPath: text('report_pdf_local_path'),
  reportPdfRemoteUrl: text('report_pdf_remote_url'),
  createdByUserId: text('created_by_user_id'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  status: text('status').notNull().default('Draft'),
});

export const ssRooftopAssessments = pgTable('ss_rooftop_assessments', {
  id: text('id').primaryKey(),
  ...syncCols,
  siteId: text('site_id'),
  siteName: text('site_name').notNull(),
  buildingIdName: text('building_id_name').notNull(),
  heritageStatus: text('heritage_status'),
  heritageDealBreaker: boolean('heritage_deal_breaker').notNull().default(false),
  aerialPhotoUri: text('aerial_photo_uri'),
  roofAreaTotalM2: real('roof_area_total_m2'),
  roofMaterial: text('roof_material'),
  roofFramingType: text('roof_framing_type'),
  roofPitchAngle: text('roof_pitch_angle'),
  roofConstructionMaterial: text('roof_construction_material'),
  asbestosFlag: boolean('asbestos_flag').notNull().default(false),
  roofCondition: text('roof_condition'),
  roofEstimatedAge: text('roof_estimated_age'),
  roofOrientationPrimary: text('roof_orientation_primary'),
  roofShadingSources: text('roof_shading_sources'),
  roofShadingUsablePct: text('roof_shading_usable_pct'),
  roofOrientationShading: text('roof_orientation_shading'),
  structuralFeasibility: text('structural_feasibility'),
  structuralRiskFlag: boolean('structural_risk_flag').notNull().default(false),
  roofAreaUsableM2: real('roof_area_usable_m2'),
  pvSizeKwDc: real('pv_size_kw_dc'),
  acExportKw: real('ac_export_kw'),
  accessSafetyConstraints: text('access_safety_constraints'),
  switchboards: jsonb('switchboards').notNull().default([]),
  msbDetails: text('msb_details'),
  msbPhotoUri: text('msb_photo_uri'),
  existingGeneration: text('existing_generation'),
  distanceToConnectionM: real('distance_to_connection_m'),
  electricalPitsEntry: text('electrical_pits_entry'),
  inverterSiting: text('inverter_siting'),
  transformerSupplyCapacity: text('transformer_supply_capacity'),
  dnspConstraints: text('dnsp_constraints'),
  loadProfileMetering: text('load_profile_metering'),
  otherConsiderations: jsonb('other_considerations').notNull().default([]),
  siteRepFeedback: text('site_rep_feedback'),
  viabilityStatus: text('viability_status'),
  dealBreakerReason: text('deal_breaker_reason'),
  ragPriority: text('rag_priority'),
  keyAssumptionsGaps: text('key_assumptions_gaps'),
  additionalPhotos: jsonb('additional_photos').notNull().default([]),
  photoMetadata: jsonb('photo_metadata').notNull().default({}),
  createdByUserId: text('created_by_user_id'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  status: text('status').notNull().default('Draft'),
});
