CREATE TABLE "ea_additional_switchboards" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"name" text NOT NULL,
	"location" text,
	"map_locator" text,
	"type" text,
	"photo" text,
	"sub_circuits_description" text,
	"comments" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_audits" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"site_name" text NOT NULL,
	"site_address" text NOT NULL,
	"inspector_name" text NOT NULL,
	"audit_date" text,
	"status" text DEFAULT 'Draft' NOT NULL,
	"report_pdf_local_path" text,
	"report_pdf_remote_url" text,
	"created_by_user_id" text,
	"assigned_inspector_user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_forklift_chargers" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"charger_type" text NOT NULL,
	"charger_photo" text,
	"brand_model" text,
	"rating" text,
	"charger_label_photo" text,
	"power_supply" text,
	"electric_connection_photo" text,
	"location" text,
	"quantity" integer,
	"charger_space_photo" text,
	"connection_description" text,
	"socket_connection_photo" text,
	"local_isolator" text,
	"circuit_identifiable" text,
	"distance_to_switchboard" text,
	"space_for_additional" text,
	"hardwired_socket" text,
	"scheduling_opportunity" text,
	"energy_improvement_observations" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_general_electricity" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"question" text,
	"answer" text,
	"photos" text[] DEFAULT '{}' NOT NULL,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_general_water" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"question" text,
	"answer" text,
	"photos" text[] DEFAULT '{}' NOT NULL,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_hot_water_systems" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"dhw_details_type" text NOT NULL,
	"photo" text,
	"serial_number" text,
	"size_liters" real,
	"fuel_type" text,
	"location" text,
	"pipe_insulation" text,
	"pipe_insulation_thickness" text,
	"tempering_valve" text,
	"additional_photo" text,
	"more_dhw_systems" text,
	"additional_comments" text,
	"energy_improvement_observations" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_hvac_units" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"unit_name" text NOT NULL,
	"make" text,
	"photo" text,
	"location" text,
	"type" text,
	"model" text,
	"serial_number" text,
	"heating_capacity_kw" real,
	"cooling_capacity_kw" real,
	"power_supply_phase" text,
	"nameplate_photos" text,
	"indoor_unit_model" text,
	"indoor_unit_serial" text,
	"indoor_unit_nameplate_photo" text,
	"controller_type" text,
	"controller_model" text,
	"controller_photo" text,
	"temperature_sensor_type" text,
	"system_coverage" text,
	"energy_improvement_observations" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_lighting_systems" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"light_type" text NOT NULL,
	"brand_model" text,
	"photo" text,
	"rated_wattage" real,
	"quantity" integer,
	"fixtures_installed" text,
	"fixtures_photo" text,
	"area_location" text,
	"controls_type" text,
	"operating_hours" text,
	"mounting_height" text,
	"mounting_constraints_photo" text,
	"circuit_grouping" text,
	"sensors_photo" text,
	"access_limitations" text,
	"switchboard_photo_notes" text,
	"energy_improvement_observations" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_main_switchboards" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"name" text NOT NULL,
	"location" text,
	"map_locator" text,
	"site_nmi" text,
	"photo" text,
	"sub_circuits_description" text,
	"comments" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_solar_pv" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"zone_id" text NOT NULL,
	"audit_id" text NOT NULL,
	"system_size_kw" real,
	"roof_photo" text,
	"inverter_brand_model" text,
	"inverter_location" text,
	"inverter_label_photo" text,
	"power_supply_to_pv" text,
	"electricity_meter_photo" text,
	"available_roof_space" text,
	"roof_space_amount" text,
	"additional_solar_space_photo" text,
	"suitable_switchboard" text,
	"switchboard_photo" text,
	"switchboard_location" text,
	"cable_distance" text,
	"cable_route_description" text,
	"energy_improvement_observations" text,
	"extra_notes" text,
	"extra_photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ea_users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"full_name" text,
	"role" text DEFAULT 'inspector' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ea_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "ea_zones" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"audit_id" text NOT NULL,
	"zone_name" text NOT NULL,
	"zone_description" text,
	"photos" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "api_keys" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"hashed_key" text NOT NULL,
	"prefix" text NOT NULL,
	"app" text NOT NULL,
	"role" text NOT NULL,
	"created_by_user_id" text,
	"last_used_at" timestamp,
	"expires_at" timestamp,
	"revoked_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "photo_registry" (
	"id" text PRIMARY KEY NOT NULL,
	"checksum" text NOT NULL,
	"remote_url" text,
	"onedrive_item_id" text,
	"app" text NOT NULL,
	"parent_id" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"field_name" text NOT NULL,
	"file_size_bytes" integer,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refresh_tokens" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"app" text NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"revoked_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ss_rooftop_assessments" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"site_id" text,
	"site_name" text NOT NULL,
	"building_id_name" text NOT NULL,
	"heritage_status" text,
	"heritage_deal_breaker" boolean DEFAULT false NOT NULL,
	"aerial_photo_uri" text,
	"roof_area_total_m2" real,
	"roof_material" text,
	"roof_framing_type" text,
	"roof_pitch_angle" text,
	"roof_construction_material" text,
	"asbestos_flag" boolean DEFAULT false NOT NULL,
	"roof_condition" text,
	"roof_estimated_age" text,
	"roof_orientation_primary" text,
	"roof_shading_sources" text,
	"roof_shading_usable_pct" text,
	"roof_orientation_shading" text,
	"structural_feasibility" text,
	"structural_risk_flag" boolean DEFAULT false NOT NULL,
	"roof_area_usable_m2" real,
	"pv_size_kw_dc" real,
	"ac_export_kw" real,
	"access_safety_constraints" text,
	"switchboards" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"msb_details" text,
	"msb_photo_uri" text,
	"existing_generation" text,
	"distance_to_connection_m" real,
	"electrical_pits_entry" text,
	"inverter_siting" text,
	"transformer_supply_capacity" text,
	"dnsp_constraints" text,
	"load_profile_metering" text,
	"other_considerations" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"site_rep_feedback" text,
	"viability_status" text,
	"deal_breaker_reason" text,
	"rag_priority" text,
	"key_assumptions_gaps" text,
	"additional_photos" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"photo_metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_by_user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"status" text DEFAULT 'Draft' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ss_sites" (
	"id" text PRIMARY KEY NOT NULL,
	"server_id" text,
	"sync_status" text DEFAULT 'local' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"site_name" text NOT NULL,
	"location" text,
	"date_of_assessment" text,
	"document_classification" text,
	"electrical_infrastructure_summary" text,
	"known_constraints" text,
	"load_profile_metering_summary" text,
	"ppa_asset_demarcation" text,
	"appendix_notes" text,
	"appendix_items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"report_pdf_local_path" text,
	"report_pdf_remote_url" text,
	"created_by_user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"status" text DEFAULT 'Draft' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ss_users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"full_name" text,
	"role" text DEFAULT 'inspector' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "ss_users_email_unique" UNIQUE("email")
);
